language: node_js
node_js:
  - 7
cache: yarn
before_install:
  - cd functions
  - yarn install
  - cd ..
before_script:
  - npm install -g firebase-tools
  - yarn install
script:
  - yarn test
after_success:
  - yarn run build
  - yarn run deploy
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

